In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3]])

In [3]:
b = np.array([[2],[3],[4]])

In [4]:
a

array([[1, 2, 3]])

In [5]:
b

array([[2],
       [3],
       [4]])

In [6]:
np.dot(b,a)

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [9]:
np.outer(b,a)

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [10]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
ones = np.array([[1]]*10)

In [14]:
ones

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])